version: '3'

services:
  blackfury0:
    image: blackchain/blackfury:latest
    ports:
      - 1317:1317
      - 26656:26656
      - 26657:26657
    environment:
      CHAINNET: ${CHAINNET0}
      MONIKER: blackfury0
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: ${IPADDR0}
    volumes:
      - ./blackfury/root/scripts:/root/scripts:Z
    command: /root/scripts/blackfury.sh
    networks:
      blackchain:
        ipv4_address: ${IPADDR0}

  blackfury1:
    image: blackchain/blackfury:latest
    ports:
      - 2317:1317
      - 36656:26656
      - 36657:26657
    environment:
      CHAINNET: ${CHAINNET1}
      MONIKER: blackfury1
      MNEMONIC: ${MNEMONIC}
      BIND_IP_ADDRESS: ${IPADDR1}
    volumes:
      - ./blackfury/root/scripts:/root/scripts:Z
    command: /root/scripts/blackfury.sh
    networks:
      blackchain:
        ipv4_address: ${IPADDR1}

  ts-relayer:
    image: blackchain/ts-relayer:latest
    environment:
      CHAINNET0: ${CHAINNET0}
      CHAINNET1: ${CHAINNET1}
      RELAYER_SRC: ${CHAINNET0}
      RELAYER_DEST: ${CHAINNET1}
      BLACKFURY0_MNEMONIC: ${MNEMONIC}
      BLACKFURY1_MNEMONIC: ${MNEMONIC}
      RPC0: ${IPADDR0}:26657
      RPC1: ${IPADDR1}:26657
      PREFIX0: black
      PREFIX1: black
      GAS_PRICE0: "0.5fury"
      GAS_PRICE1: "0.5fury"
    volumes:
      - ./ts-relayer/root/scripts:/root/scripts:Z
    depends_on:
      - blackfury0
      - blackfury1
    command: /root/scripts/ts-relayer.sh
    networks:
      blackchain:
        ipv4_address: ${IPADDR2}

networks:
  blackchain:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}
